### ISSUE TITLE
使用spring-boot-devtools 后, 无法注入 @Reference对象

### ISSUE THREAD

**Issue by avkojwer1** [linking12/spring-boot-starter-dubbo#1]
hi,
加入spring boot 热编译后,  @Reference对象无法被注入

```
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-devtools</artifactId>
        <optional>true</optional>
    </dependency>
```

**Comment by linking12** [comment]
dubbo的classloader是Appclassloader
热编译的classloader是org.springframework.boot.devtools.restart.classloader.RestartClassLoader
两者classloader不同导致了无法获取代理对象
如果要真正修改的话，会涉及改动dubbo的内核，这个对你影响大吗？
如果要修改的话建议自行修改dubbo的源码
请看下com.alibaba.dubbo.common.bytecode.Proxy.getProxy(Class<?>... ics)

**Comment by linking12** [comment]
这个问题的根源是热部署的时候使用的classloader和dubbo获取代理对象使用的classloader不一致导致的；
热部署使用的classloader是org.springframework.boot.devtools.restart.classloader.RestartClassLoader
dubbo获取代理对象使用的classloader是AppClassLoader
修改的话：
需要更改dubbo的代码：
/**
     \* Get proxy.
     \* 
     \* @param ics interface class array.
     \* @return Proxy instance.
     */
    public static Proxy getProxy(Class<?>... ics)
    {
        return getProxy(ClassHelper.getCallerClassLoader(Proxy.class), ics);
    }

更改为:
     public static Proxy getProxy(Class<?>... ics)
    {
        return getProxy(ClassHelper.getClassLoader(Proxy.class), ics);
    }
这个改动的话，最好是自行更改并测试下，不是spring boot插件的范围

**Comment by avkojwer1** [comment]
好的, 感谢
